services:
  - type: web
    name: mythos-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        fromDatabase:
          name: mythos-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: CORS_ORIGINS
        value: https://mythos-frontend.onrender.com

  - type: web
    name: mythos-frontend
    env: node
    buildCommand: |
      cd client
      rm -rf node_modules package-lock.json
      export NODE_VERSION=18.17.0
      export NODE_ENV=production
      export CI=false
      export HOST=0.0.0.0
      export DANGEROUSLY_DISABLE_HOST_CHECK=true
      npm install
      npm run build
    startCommand: cd client && PORT=$PORT node server.js
    envVars:
      - key: REACT_APP_API_URL
        value: https://mythos-backend.onrender.com
      - key: HOST
        value: 0.0.0.0
      - key: DANGEROUSLY_DISABLE_HOST_CHECK
        value: true
      - key: NODE_ENV
        value: production

databases:
  - name: mythos-db
    databaseName: mythos
    user: mythos