services:
  - type: web
    name: mythos-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        fromDatabase:
          name: mythos-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: CORS_ORIGINS
        value: https://mythos-frontend.onrender.com

  - type: static
    name: mythos-frontend
    buildCommand: |
      cd client
      export NODE_VERSION=18.17.0
      export NODE_ENV=production
      export CI=false
      npm install
      npm run build
    staticPublishPath: client/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: mythos-db
    databaseName: mythos
    user: mythos