services:
  - type: web
    name: mythos-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        fromDatabase:
          name: mythos-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: CORS_ORIGINS
        value: https://mythos-frontend.onrender.com

  - type: web
    name: mythos-frontend
    env: static
    buildCommand: |
      cd client
      npm install
      CI=false npm run build
    staticPublishPath: client/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://mythos-backend.onrender.com

databases:
  - name: mythos-db
    databaseName: mythos
    user: mythos 