"""trying again

Revision ID: 088adcea8d79
Revises: 71a45bd89d6d
Create Date: 2025-03-25 11:00:28.793495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '088adcea8d79'
down_revision = '71a45bd89d6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('wallet',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('wallet',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
