"""added pets table

Revision ID: 32a73213ea15
Revises: 088adcea8d79
Create Date: 2025-03-25 13:15:37.314439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32a73213ea15'
down_revision = '088adcea8d79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('animal_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pets'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pets')
    # ### end Alembic commands ###
