"""Initial migration

Revision ID: 71a45bd89d6d
Revises: 
Create Date: 2025-03-20 13:14:26.010419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71a45bd89d6d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deck_cards')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deck_cards',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('deck_id', sa.INTEGER(), nullable=False),
    sa.Column('card_id', sa.INTEGER(), nullable=False),
    sa.Column('position', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], name='fk_deck_cards_card_id_cards'),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], name='fk_deck_cards_deck_id_decks'),
    sa.PrimaryKeyConstraint('id', name='pk_deck_cards')
    )
    # ### end Alembic commands ###
